# Generated by Django 6.0.5 on 2026-06-02 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Oficiales de Cubierta, Mando, Tripulación', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectorMaritimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Marina Mercante, Naves Menores, Pesca Industrial', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Patrón de Nave Menor, Piloto Primero', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='portal_trabajo.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nave_o_proyecto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('salario_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('cargo_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_trabajo.cargoespecialidad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_publicadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilMaritimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libreta_embarque', models.CharField(blank=True, help_text='N° de Libreta o Matrícula', max_length=50, null=True)),
                ('puerto_base', models.CharField(blank=True, help_text='Ej: Puerto Montt', max_length=100, null=True)),
                ('experiencia_anios', models.PositiveIntegerField(default=0)),
                ('cargo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_trabajo.cargoespecialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='portal_trabajo.sectormaritimo'),
        ),
    ]
